### ISSUE TITLE
rosserial lino_msgs generation

### ISSUE THREAD

**Issue by BlockByBlock** [linorobot/lino_install#2]
source $HOME/linorobot_ws/devel/setup.bash must be done before rosrun rosserial make_libraries.py

without which the lino_msgs will not be available on rospack list for the make_libraries node to generate necessary rosmsg

**Comment by grassjelly** [comment]
Hi Bing, 

These lines are included in the latest commit  -  right after the lino_msgs is cloned https://github.com/linorobot/lino_install/blob/master/install/#L97-L98 . May I know which line does it fail

**Comment by BlockByBlock** [comment]
Great, it should work
